---
output: 
  word_document:
    reference_docx: Meta_Data/template_annual.docx
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "Output_Documents") })
---
```{r Species Trends setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("global_markdown.R")
oneM_Data <-  readr::read_csv("Tidy_Data_Dont_Touch/oneM_Summary.csv")

fiveM_Data <-  readr::read_csv("Tidy_Data_Dont_Touch/fiveM_Summary.csv")

bands_Data <-  readr::read_csv("Tidy_Data_Dont_Touch/bands_Summary.csv")

rdfc_Data <-  readr::read_csv("Tidy_Data_Dont_Touch/RDFC_Summary.csv")

Benthic_Density_Long <- base::rbind(oneM_Data, fiveM_Data, bands_Data) %>% 
  dplyr::filter(SiteNumber %in% 1:16) %>% 
  dplyr::mutate(IslandName = factor(IslandName, levels = IslandLevelsFull),
                SiteName = factor(SiteName, levels = SiteLevels))


Par_par_sc <- Benthic_Density_Long %>% 
  dplyr::filter(ScientificName == "Parastichopus parvimensis",
                IslandCode == "SC") %>% 
  base::droplevels()
Par_par_an <- Benthic_Density_Long %>% 
  dplyr::filter(ScientificName == "Parastichopus parvimensis",
                IslandCode == "AN") %>% 
  base::droplevels()
Par_par_sb <- Benthic_Density_Long %>% 
  dplyr::filter(ScientificName == "Parastichopus parvimensis",
                IslandCode == "SB") %>% 
  base::droplevels()

Lobsta_sc <- Benthic_Density_Long %>% 
  dplyr::filter(ScientificName == "Panulirus interruptus",
                IslandCode == "SC") %>% 
  base::droplevels()
Lobsta_an <- Benthic_Density_Long %>% 
  dplyr::filter(ScientificName == "Panulirus interruptus",
                IslandCode == "AN") %>% 
  base::droplevels()
Lobsta_sb <- Benthic_Density_Long %>% 
  dplyr::filter(ScientificName == "Panulirus interruptus",
                IslandCode == "SB") %>% 
  base::droplevels()
```

```{r Par Par 1, warning=FALSE, message=FALSE, fig.height=5.5, fig.width=11}

parpar <- readr::read_csv(
  glue("Raw_DB_Files_SAVE_HERE/KFM_1mQuadrat_RawData_1982-{Export_END_Year}.txt"),   
  col_types = cols(CountA = col_number(), CountB = col_number())) %>%
  dplyr::filter(IslandCode != "CL") %>%
  dplyr::left_join(siteInfo1) %>%
  tidyr::separate(SurveyDate, c('Date','Time'),' ') %>%
  dplyr::mutate(Date = as.Date(Date, format='%m/%d/%Y')) %>% 
  tidyr::pivot_longer(cols = c(CountA, CountB), values_to = "Count") %>% 
  dplyr::filter(!is.na(Count), !is.na(CommonName)) %>% 
  dplyr::select(SiteNumber, IslandCode, IslandName, SiteCode, SiteName, Species, ScientificName,
                CommonName, SurveyYear, Date, QuadratNumber, Count, ReserveStatus, MeanDepth, 
                Reference, Old_New_Comp, ReserveYear) %>% 
  dplyr::filter(ScientificName == "Parastichopus parvimensis",
                Old_New_Comp == TRUE) %>% 
  dplyr::group_by(SiteNumber, IslandCode, IslandName, SiteCode, SiteName,  ScientificName,
                  Species, CommonName, Old_New_Comp, ReserveYear,
                  SurveyYear, Date, ReserveStatus, MeanDepth, Reference) %>%
  dplyr::summarise(Count_To_Reuse = Count,
                   Area_Surveyed = ifelse(SurveyYear %in% 1985:1994, n() * 2, n()),
                   Total_Count = sum(Count),
                   Mean_Density = round(Total_Count / Area_Surveyed, 4), 
                   SD = round(sd(Count), 4),
                   SE = round(SD / sqrt(Area_Surveyed), 4)) %>% 
  dplyr::ungroup() %>%  
  dplyr::select(SiteNumber, IslandCode, IslandName, SiteCode, SiteName, 
                Species, CommonName,
                ScientificName,SurveyYear, 
                Date, Total_Count, Mean_Density, SD, SE, Area_Surveyed,
                ReserveStatus, MeanDepth, Reference, Old_New_Comp, ReserveYear) %>%
  dplyr::distinct(SiteNumber, IslandCode, IslandName, SiteCode, SiteName,
                  Species, CommonName, ScientificName, SurveyYear, 
                  Total_Count, Mean_Density, SD, SE, Area_Surveyed, .keep_all = TRUE)




ggplot(parpar,
       aes(x = SurveyYear, y = Mean_Density, color = ReserveYear, linetype = ReserveYear)) + 
  ggplot2::stat_smooth(geom='ribbon', alpha = .2, linetype = 0, 
                       aes(ymin = ifelse(..ymin.. <0, 0, ..ymin..))) +
  geom_smooth(size = 1, se = FALSE, alpha = 1) +
  geom_vline(aes(xintercept = 1993), size = 1) +
  geom_label(aes(x = 1993, y = Inf, vjust = 1, hjust = 1, label = "Dive Fishery Begins"), color = "black") +
  geom_vline(aes(xintercept = 2003), size = 1) +
  geom_label(aes(x = 2003, y = Inf, vjust = 1, hjust = 1, label = "New MPAs Created"), color = "black") +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = parpar$ScientificName,  
       subtitle = parpar$CommonName,
       color = "Reserve Year", linetype = "Reserve Year",
       # caption = "Data from 11 of the 16 original KFM sites at Santa Cruz Island, Anacapa Island, and Santa Barbara Island. \nTwo sites make up the 1978 reserve, Cathedral Cove and Landing Cove. \nThree sites make up the 2003 reserve, Gull Island South, Scorpion Anchorage, and Southeast Sea Lion. \nSix sites make up outside the reserves, Fry's Harbor, Pelican Bay, Yellow Banks, Admiral's Reef, Arch Point, and Cat Canyon",
       x = "Survey Year", y = "Mean Density") +
  ggpubr::theme_classic2() +
    ggplot2::theme(plot.title = element_text(hjust = 0.5, size = 20, face = "italic"),
                   plot.subtitle = element_text(hjust = 0.5, size = 16),
                   plot.caption = element_text(size = 10, hjust = 0),
                   legend.position = "right",
                   legend.justification = c(0,0.5),
                   legend.key.width = unit(.75, "cm"),
                   legend.background = element_rect(size = unit(5, "cm")),
                   legend.title = element_text(size = 12, color = "black"),
                   legend.text = element_text(size = 10, colour = "black"),
                   panel.grid.major = element_line(),
                   axis.title = element_text(hjust = .5, size = 14),
                   axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12),
                   axis.text = element_text(size = 12),
                   strip.text = element_text(size = 10, colour = "black", angle = 90))
```

```{r loby lob, warning=FALSE, message=FALSE, fig.height=5.5, fig.width=11}
loby <- read_csv(
  glue("Raw_DB_Files_SAVE_HERE/KFM_BandTransect_RawData_1982-{Export_END_Year}.txt"),   
  col_types = cols(CountA = col_number(), CountB = col_number())) %>%
  dplyr::filter(IslandCode != "CL") %>%
  dplyr::left_join(siteInfo1) %>%
  tidyr::separate(SurveyDate, c('Date','Time'),' ') %>%
  dplyr::mutate(Date = as.Date(Date, format='%m/%d/%Y')) %>%
  tidyr::pivot_longer(cols = c(CountA, CountB), values_to = "Count") %>% 
  dplyr::filter(!is.na(Count), !is.na(CommonName)) %>% 
  dplyr::select(SiteNumber, IslandCode, IslandName, SiteCode, SiteName, Species, ScientificName,
                CommonName, SurveyYear, Date, TransectNumber, Count, ReserveStatus, MeanDepth,
                Reference, Old_New_Comp, ReserveYear) %>% 
  dplyr::group_by(SiteNumber, ScientificName, CommonName, SurveyYear, TransectNumber) %>%
  dplyr::mutate(Count = sum(Count, na.rm = TRUE)) %>% 
  dplyr::ungroup() %>%
  dplyr::distinct(SiteNumber, ScientificName, SurveyYear, TransectNumber, Count, .keep_all = TRUE)  %>% 
  dplyr::filter(ScientificName == "Panulirus interruptus",
                Old_New_Comp == TRUE) %>% 
  dplyr::group_by(SiteNumber, IslandCode, IslandName, SiteCode, SiteName,  ScientificName,
                  Species, CommonName, Old_New_Comp, ReserveYear,
                  SurveyYear, Date, ReserveStatus, MeanDepth, Reference) %>%
  dplyr::summarise(Count_To_Reuse = Count,
                   Area_Surveyed = ifelse(SurveyYear %in% 1983:1984, n() * 40, n() *60), 
                   Total_Count = sum(Count),
                   Mean_Density = round(Total_Count / Area_Surveyed, 4), 
                   SD = round(sd(Count), 4),
                   SE = round(SD/sqrt(Area_Surveyed), 4)) %>% 
  dplyr::ungroup() %>%  
  dplyr::select(SiteNumber, IslandCode, IslandName, SiteCode, SiteName, 
                Species, CommonName,
                ScientificName,SurveyYear, 
                Date, Total_Count, Mean_Density, SD, SE, Area_Surveyed,
                ReserveStatus, MeanDepth, Reference, Old_New_Comp, ReserveYear) %>%
  dplyr::distinct(SiteNumber, IslandCode, IslandName, SiteCode, SiteName,
                  Species, CommonName, ScientificName, SurveyYear, 
                  Total_Count, Mean_Density, SD, SE, Area_Surveyed, .keep_all = TRUE)

ggplot(loby,
       aes(x = SurveyYear, y = Mean_Density, color = ReserveYear, linetype = ReserveYear)) + 
  ggplot2::stat_smooth(geom='ribbon', alpha = .2, linetype = 0, 
                       aes(ymin = ifelse(..ymin.. <0, 0, ..ymin..))) +
  geom_smooth(size = 1, se = FALSE, alpha = 1) +
  geom_vline(aes(xintercept = 2003), size = 1) +
  geom_label(aes(x = 2003, y = Inf, vjust = 1, hjust = 1, label = "New MPAs Created"), color = "black") +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = loby$ScientificName,  
       subtitle = loby$CommonName,
       color = "Reserve Year", linetype = "Reserve Year",
       # caption = "Data from 11 of the 16 original KFM sites at Santa Cruz Island, Anacapa Island, and Santa Barbara Island. \nTwo sites make up the 1978 reserve, Cathedral Cove and Landing Cove. \nThree sites make up the 2003 reserve, Gull Island South, Scorpion Anchorage, and Southeast Sea Lion. \nSix sites make up outside the reserves, Fry's Harbor, Pelican Bay, Yellow Banks, Admiral's Reef, Arch Point, and Cat Canyon",
       x = "Survey Year", y = "Mean Density") +
  ggpubr::theme_classic2() +
    ggplot2::theme(plot.title = element_text(hjust = 0.5, size = 20, face = "italic"),
                   plot.subtitle = element_text(hjust = 0.5, size = 16),
                   plot.caption = element_text(size = 10, hjust = 0),
                   legend.position = "right",
                   legend.justification = c(0,0.5),
                   legend.key.width = unit(.75, "cm"),
                   legend.background = element_rect(size = unit(5, "cm")),
                   legend.title = element_text(size = 12, color = "black"),
                   legend.text = element_text(size = 10, colour = "black"),
                   panel.grid.major = element_line(),
                   axis.title = element_text(hjust = .5, size = 14),
                   axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12),
                   axis.text = element_text(size = 12),
                   strip.text = element_text(size = 10, colour = "black", angle = 90))
```

```{r Par Par, warning=FALSE, message=FALSE, fig.height=8.5, fig.width=11}
ggplot2::theme_set(
  ggpubr::theme_classic2() +
    ggplot2::theme(plot.title = element_text(hjust = 0.5, size = 20, face = "italic"),
                   plot.subtitle = element_text(hjust = 0.5, size = 16),
                   legend.position = "right",
                   legend.justification = c(0,0.5),
                   legend.key.width = unit(.75, "cm"),
                   legend.background = element_rect(size = unit(5, "cm")),
                   legend.title = element_text(size = 12, color = "black"),
                   legend.text = element_text(size = 10, colour = "black"),
                   panel.grid.major = element_line(),
                   axis.title = element_text(hjust = .5, size = 14),
                   axis.text.x = element_blank(),
                   axis.text.y = element_text(size = 12),
                   strip.text = element_text(size = 10, colour = "black", angle = 90))
)
SC_Par_par <- ggplot(Par_par_sc,
       aes(x = SurveyYear, y = Mean_Density, color = SiteName, linetype = SiteName)) + 
  geom_smooth(size = 1, se = FALSE) +
  geom_vline(aes(xintercept = 1993), size = 1) +
  geom_label(aes(x = 1993, y = Inf, vjust = 1, hjust = 1, label = "Dive Fishery Begins"), color = "black") +
  geom_vline(aes(xintercept = 2003), size = 1) +
  geom_label(aes(x = 2003, y = Inf, vjust = 1, hjust = 1, label = "MPAs Created"), color = "black") +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = Par_par_sc$ScientificName,  
       subtitle = Par_par_sc$CommonName,
       color = "Site Name", linetype = "Site Name",
       x = NULL, y = NULL) +
  facet_grid(rows = vars(IslandName), scales = "free") +
  scale_color_manual(values = SiteColor, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  scale_linetype_manual(values = SiteLine, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  theme_get()

AN_Par_par <- ggplot(Par_par_an,
       aes(x = SurveyYear, y = Mean_Density, color = SiteName, linetype = SiteName)) + 
  geom_smooth(size = 1, se = FALSE) +
  geom_vline(aes(xintercept = 1993), size = 1) +
  geom_vline(aes(xintercept = 2003), size = 1) +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = NULL, subtitle = NULL,
       color = "Site Name", linetype = "Site Name",
       x = NULL, y = NULL) +
  facet_grid(rows = vars(IslandName), scales = "free") +
  scale_color_manual(values = SiteColor, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  scale_linetype_manual(values = SiteLine, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  theme_get()

SB_Par_par <- ggplot(Par_par_sb,
       aes(x = SurveyYear, y = Mean_Density, color = SiteName, linetype = SiteName)) + 
  geom_smooth(size = 1, se = FALSE) +
  geom_vline(aes(xintercept = 1993), size = 1) +
  geom_vline(aes(xintercept = 2003), size = 1) +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = NULL, subtitle = NULL,
       color = "Site Name", linetype = "Site Name",
       x = "Year", y = NULL) +
  facet_grid(rows = vars(IslandName), scales = "free") +
  scale_color_manual(values = SiteColor, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  scale_linetype_manual(values = SiteLine, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12))

  plot <- ggpubr::ggarrange(SC_Par_par, AN_Par_par, SB_Par_par, ncol = 1, align = "v", heights = c(2,1.5,1.9),
                            common.legend = FALSE)
  a <- ggpubr::annotate_figure(
    plot,
    bottom = text_grob("1 m² Quadrat Data",
                       color = "black", size = 14, hjust = 0, x = 0),
    left = text_grob("Mean Density/m²", color = "black", rot = 90, size = 18)
  )
  print(a)

```
```{r Lobsta, warning=FALSE, message=FALSE, fig.height=8.5, fig.width=11}
ggplot2::theme_set(
  ggpubr::theme_classic2() +
    ggplot2::theme(plot.title = element_text(hjust = 0.5, size = 20, face = "italic"),
                   plot.subtitle = element_text(hjust = 0.5, size = 16),
                   legend.position = "right",
                   legend.justification = c(0,0.5),
                   legend.key.width = unit(.75, "cm"),
                   legend.background = element_rect(size = unit(5, "cm")),
                   legend.title = element_text(size = 12, color = "black"),
                   legend.text = element_text(size = 10, colour = "black"),
                   panel.grid.major = element_line(),
                   axis.title = element_text(hjust = .5, size = 14),
                   axis.text.x = element_blank(),
                   axis.text.y = element_text(size = 12),
                   strip.text = element_text(size = 10, colour = "black", angle = 90))
)
SC_Par_par <- ggplot(Lobsta_sc,
       aes(x = SurveyYear, y = Mean_Density, color = SiteName, linetype = SiteName)) + 
  geom_smooth(size = 1, se = FALSE) +
  geom_vline(aes(xintercept = 2003), size = 1) +
  geom_label(aes(x = 2003, y = Inf, vjust = 1, hjust = 1, label = "MPAs Created"), color = "black") +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = Lobsta_sc$ScientificName,  
       subtitle = Lobsta_sc$CommonName,
       color = "Site Name", linetype = "Site Name",
       x = NULL, y = NULL) +
  facet_grid(rows = vars(IslandName), scales = "free") +
  scale_color_manual(values = SiteColor, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  scale_linetype_manual(values = SiteLine, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  theme_get()

AN_Par_par <- ggplot(Lobsta_an,
       aes(x = SurveyYear, y = Mean_Density, color = SiteName, linetype = SiteName)) + 
  geom_smooth(size = 1, se = FALSE) +
  geom_vline(aes(xintercept = 2003), size = 1) +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = NULL, subtitle = NULL,
       color = "Site Name", linetype = "Site Name",
       x = NULL, y = NULL) +
  facet_grid(rows = vars(IslandName), scales = "free") +
  scale_color_manual(values = SiteColor, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  scale_linetype_manual(values = SiteLine, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  theme_get()

SB_Par_par <- ggplot(Lobsta_sb,
       aes(x = SurveyYear, y = Mean_Density, color = SiteName, linetype = SiteName)) + 
  geom_smooth(size = 1, se = FALSE) +
  geom_vline(aes(xintercept = 2003), size = 1) +
  scale_x_continuous(breaks = c(1982:Year_to_Filter_Data_by), expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(title = NULL, subtitle = NULL,
       color = "Site Name", linetype = "Site Name",
       x = "Year", y = NULL) +
  facet_grid(rows = vars(IslandName), scales = "free") +
  scale_color_manual(values = SiteColor, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  scale_linetype_manual(values = SiteLine, guide = guide_legend(
    title.position = "top", title.hjust = .5, ncol = 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12))

  plot <- ggpubr::ggarrange(SC_Par_par, AN_Par_par, SB_Par_par, ncol = 1, align = "v", heights = c(2,1.5,1.9),
                            common.legend = FALSE)
  a <- ggpubr::annotate_figure(
    plot,
    bottom = text_grob("1 m² Quadrat Data",
                       color = "black", size = 14, hjust = 0, x = 0),
    left = text_grob("Mean Density/m²", color = "black", rot = 90, size = 18)
  )
  print(a)

```
